<style type="text/css">
.mapbubbletitle { 
  font-weight:bold; 
  font-size: 13px;
  color: #006699; 
} 
.mapbubble { 
  margin: 0px 0px 0px 0px; 
  padding: 0px 0px 0px 0px; 
  font-size: 13px;
  width:300px;
}
.mappicture{
  float:right;
  margin-right:10px;
}
</style>

<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyB8l-4-oAlAW16pHHcQ2ncSxofVZx3b8l8&sensor=false"> </script> 
<script type="text/javascript" src="https://cooldisplays.net/maptools.php"> </script>

Our display is located at <a href="https://goo.gl/maps/tZj7PPjBcjEFB1XM6">6656 Devon Drive in Liberty Township, OH</a>  near a number of other enjoyable holiday displays.
   <div id ="map" style="width:auto; height:400px; margin-top:10px; margin-bottom:10px;"></div> 
   <div class="bottom-logo">
      <a href="https://cooldisplays.net/index.php?page=single&id=1">
         <img src="https://cooldisplays.net/picture.php?logo=1&width=300" style="padding:20px;">
      </a>
   </div>

<script type = "text/javascript">
coolMap.showMap(1, 10, 'map'); 
</script>
