<?php 
$title="Christmas 2004-2007 at the Hormanns";
$subTitle="Christmas 2004-2007";
include "intro.phtml" ?>

<div class="container-fluid"><!--Main Container -->

<center>
<?php Christmas_years(); ?>
</center>

<div class="row">
<div class="col-sm-8">
<h1>Christmas 2004-2007 at the Hormanns</h1>
2004 was our forth year for an animated Christmas display.  A number of
changes were made in 2004 (described below) and the display remains
mostly the same 2004-2007. 
<br><br>
In 2004, the real focus was on hardware
and software instead of adding more lights. The vast majority
of the display is still controlled by 
the <a href="parallel320.phtml">320 Circuit Controller</a>.
We used 70 of the available 320 circuits for The 
Clock, Merry Christmas Sign, and The Snowmen. We converted the 
bushes to use <a href="http://www.lightorama.com/">LOR Hobbyist</a>
boxes (4 boxes for a total of 32 circuits). These boxes support fading 
in addition to on/off circuits. Greg spend quite a bit of time developing a 
FreeBSD driver so that we could control the LOR components from 
the same software as the 320 Controller. (Why not just uses the purchased 
software from Lights-O-Rama?  Greg wanted a challenge!)

<br><br>
The two must viewer noticeable changes over last year are (1) the bushes now
fade between colors resulting in a softer display and (2) the addition
of the "Merry Christmas" sign above the garage door.


<h2>Movies</h2>
<em>Note: Requires  <a href="http://www.real.com"> Real Player</a> 9 
or higher</em>
<br><br>
<center>
<table border=0 cellpadding=20>
<tr>
<td align="center">
     <img src="christmas/2003/thumbnails/IMG_0868.JPG"><br>
     Clock (<a href="christmas/2003/movies/sign.rm">Real</a>) (1MB)
</td>

<td align="center">
     <img src="christmas/2003/thumbnails/IMG_0872.JPG"><br>
     House (<a href="christmas/2004/bushes.rm">Real</a>) (5.8MB)
</td>
</tr>
<tr>
<td align="center">
     <img src="christmas/2003/thumbnails/IMG_0894.JPG"><br>
     Snowmen (<a href="christmas/2002/movies/snowmen.rm">Real</a>) (4MB)
</td>
<td align="center">
     <img src="christmas/2004/Outside/thumbnails/IMG_5999.JPG" width=200 height=150><br>
     Merry Christmas Sign (<a href="christmas/2004/sign.rm">Real</a>) (4MB)
</td>

</TR>
</TABLE>
</center>
<br><br>

</div><!--sm-8-->
<div class="col-sm-4">
<?php include "favDisplays.phtml" ?>
</div><!-- Sm-4 -->
</div><!--Row -->

<h2>Statistics</h2>
<ul>
<li> ~13000 lights
<li> 102 Circuits
<li> ~2000 ft electrical and control Wire
<li> P-75 Mhz PC
</ul>

<h2>Pictures</h2>
<font size=-2 color="brown">(Click image to enlarge)</font>
<br>

<a href="christmas/2004/Outside/normal_size/IMG_5997.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_5997.JPG border=1></a>

<a href="christmas/2004/Outside/normal_size/IMG_5999.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_5999.JPG border=1></a>

<a href="christmas/2004/Outside/normal_size/IMG_6000.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6000.JPG border=1></a>

<a href="christmas/2004/Outside/normal_size/IMG_6001.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6001.JPG border=1></a>

<a href="christmas/2004/Outside/normal_size/IMG_6209.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6209.JPG border=1></a>
<br><br><br>


<h2>Behind the Scenes</h2>

Currently, we just have 
<a href="christmas/2004/computer.rm">quick video </a>
showing the 
output on the computer screen.
This screen is mainly used for debugging the program and shows
everything that is happening outside.


<br><br><br>


<h2>Source Code</h2>

<center>
<table border=0>
<tr>
<td><a href="christmas/2004/source/main.c.txt">main.c</a></td>
<td><a href="christmas/2004/source/bushes.c.txt">bushes.c</a></td>
</tr><tr>
<td><a href="christmas/2004/source/Makefile.txt">Makefile</a></td>
<td><a href="christmas/2004/source/sign.c.txt">sign.c</a></td>
</tr><tr>
<td><a href="christmas/2004/source/main.h.txt">main.h</a></td>
<td><a href="christmas/2004/source/snowmen.c.txt">snowmen.c</a></td>
</tr><tr>
<td><a href="christmas/2004/source/clock.c.txt">clock.c</a></td>
</tr><tr>
<td><a href="christmas/2004/source/lor.c.txt">lor.c</a></td>
<td><a href="christmas/2004/source/lor.h.txt">lor.h</a></td>
</tr><tr>
<td><a href="christmas/2004/source/320controller.c.txt">320controller.c</a></td>
<td><a href="christmas/2004/source/320controller.h.txt">320controller.h</a></td>
</tr>
</table>
</center>

<br><br>
</center>

</div><!-- main -->

<?php include "footer.phtml" ?>

