<?php 
$title="Christmas 2008-2009 at the Hormanns";
$subTitle="Christmas 2008-2009";
include "intro.phtml" ?>

<div class="container-fluid"><!--Main Container -->

<center>
<?php Christmas_years(); ?>
</center>
<div class="row">
<div class="col-sm-8">
<h1>Christmas 2008-2009 at the Hormann's</h1>

2008 was our eight year for an animated Christmas display.  
Once again Mary and I had big plans for increasing the size of the display
but with two kids, we just didn't find the time.  This year the 
<a href="parallel320.phtml">320 Circuit Controller</a> completely died.  
Over the last few years there had been a few problems with some circuits
getting stuck on, or turning on when others circuits where turned on, but
this year it was really bad with most of the circuits having problems.  After
spending two hours trying to "fix" the issue by replacing individual chips,
I finally just pulled every single chip from the board and put in new 
ones.  (My belief was that one had gone bad and was burning up new chips
that were being put in. That should would explain why a new chip started 
smoking after replaced it.)  Luckily, I had enough spares laying around.
Replacing every single chip at the same time worked! As always the 
<a href="https://www.lightorama.com/">LOR Hobbyist</a>
boxes worked perfectly. 

<br><br>
Although we didn't make any big additions, there were a few changes this year.
First, I changed the software so that the clock could count down to 
New Years Eve in addition to Christmas Day.  We now just replace the word 
"Christmas" with the next year (2009) on Christmas Morning. It now takes
about 15 minutes to make the switch. <br><br>

Second, we added some new pattens for the bushes to perform. Unfortunately, 
these were added after the movies where created and don't show up. :-(

No major changes were made in 2009.  Unfortuantly, we had to replace 
some of the controllers that wore out, and do some major repairs to the 
snowmen. It is hard to believe many of the parts of the display are 10 years 
old.

<br><br>
<h2>Movies</h2>
We are hosting the movies on YouTube this year.  If you have problems 
accessing them, please let us know.  They should show up below.

<br><br>
<center>

<br><br>

<?php
   $movies = array(
             array("T9higzsvWNk", "Dancing Bushes", "https://img.youtube.com/vi/T9higzsvWNk/hqdefault.jpg"),
             array("MnXRQG9p0ps", "Countdown Clock", "https://img.youtube.com/vi/MnXRQG9p0ps/hqdefault.jpg"),
             array("Z6t6t1zBcxU", "Our Snowmen", "https://img.youtube.com/vi/Z6t6t1zBcxU/hqdefault.jpg"),
             array("XMU1wOk-iR4", "Merry Christmas", "https://img.youtube.com/vi/XMU1wOk-iR4/hqdefault.jpg"),
             array("-zaNm3LyelE", "Control Central", "https://img.youtube.com/vi/-zaNm3LyelE/hqdefault.jpg"),
   );


youtubeVideo($movies);
?>

</center>

<h2>Statistics</h2>
<ul>
<li> ~13000 lights
<li> 102 Circuits
<li> ~2000 ft electrical and control Wire
<li> P-500 Mhz PC
</ul>

<h2>Pictures</h2>
<font size=-2 color="brown">(Click image to enlarge)</font>
<br>

<div class="old-picture">
<a href="christmas/2004/Outside/normal_size/IMG_5997.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_5997.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_5999.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_5999.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_6000.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6000.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_6001.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6001.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_6209.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6209.JPG ></a>
</div>

<br><br><br>



</div><!--sm-8-->
<div class="col-sm-4">
<?php include "favDisplays.phtml" ?>
</div><!-- Sm-4 -->
</div><!-- row -->


<!--

<font color=brown>
<b><font size=5>Source Code</font></b><br>
</font>
<br>

<center>
<table border=0>
<tr>
<td><a href="christmas/2008/source/main.c.txt">main.c</a></td>
<td><a href="christmas/2008/source/bushes.c.txt">bushes.c</a></td>
</tr><tr>
<td><a href="christmas/2008/source/Makefile.txt">Makefile</a></td>
<td><a href="christmas/2008/source/sign.c.txt">sign.c</a></td>
</tr><tr>
<td><a href="christmas/2008/source/main.h.txt">main.h</a></td>
<td><a href="christmas/2008/source/snowmen.c.txt">snowmen.c</a></td>
</tr><tr>
<td><a href="christmas/2008/source/clock.c.txt">clock.c</a></td>
</tr><tr>
<td><a href="christmas/2008/source/lor.c.txt">lor.c</a></td>
<td><a href="christmas/2008/source/lor.h.txt">lor.h</a></td>
</tr><tr>
<td><a href="christmas/2008/source/320controller.c.txt">320controller.c</a></td>
<td><a href="christmas/2008/source/320controller.h.txt">320controller.h</a></td>
</tr>
</table>
</center>

-->

<br><br>
</center>
</div><!-- main -->

<?php include "footer.phtml" ?>

