<?php 
$title="Christmas 2013 at the Hormanns";
$subTitle="Christmas 2013";
include "intro.phtml" ?>

<div class="container-fluid"><!--Main Container -->

<center>
<?php Christmas_years(); ?>
</center>
<div class="row">
<div class="col-sm-8">
<h1>Christmas 2013 at the Hormann's</h1>

2013 was our thirteenth year for an animated Christmas display.  No major changes from 2012 were made.   We did add some strobe lights that go off when the countdown clock hits zero.  After over a decade of service, the <a href="snowmen.php">snowmen</a> required major repair. The rope lighting that makes up the bodies of both snowmen failed just after we finished setting them up. This wasn't nearly as bad as the wind damage of 2004 that snapped the support piping, but was interesting to see that both strands failed at exactly the same time.

<br><br>
For the last 8 years or so, a small (but growing) group of neighbors have
braved the cold to watch the clock hit mid-night and welcome Christmas.  
This year, we had 22 neighbors come and watch the clock hit zero.  You can hear them belt out the last 10 seconds at the top of their lungs in the video below.
<br><br>

<h2>Map</h2>
<?php include "christmas/display.phtml" ?>

<h2>Movies</h2>
We are hosting the movies on YouTube again.  If you have problems 
accessing them, please let us know.  They should show up below. <i>Note that 
all are available in HD. </i>

<br><br>
<center>

<?php 
   $movies = array("c5oBUImfSdA", "YY1jnphglgw", "RfnnOA3iYeo", "Y6ZcAkIPIFE", "TuTu1zv39b0");

   foreach ($movies as $mov)
   {
      echo("<a href=\"https://www.youtube.com/watch?v=$mov\">");
      echo("<img src=\"https://img.youtube.com/vi/$mov/0.jpg\" ");
      echo("style=\"border-style:none; margin: 5px 5px 5px 5px; height:250px;\">" );
      echo("</a>");
   }
?>


</center>

<br><br>


<h2>Statistics</h2>
<ul>
<li> ~13000 lights
<li> 102 Circuits
<li> ~2000 ft electrical and control Wire
<li> P-500 Mhz PC
</ul>

<h2>Pictures</h2>
<font size=-2 color="brown">(Click image to enlarge)</font>
<br>

<div class="old-picture">

<a href="christmas/2004/Outside/normal_size/IMG_5997.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_5997.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_5999.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_5999.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_6000.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6000.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_6001.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6001.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_6209.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6209.JPG ></a>
</div>
<br><br><br>



</div><!--SM-8-->

<div class="col-sm-4">
<?php include "favDisplays.phtml" ?>
</div><!-- Sm-4 -->
</div><!-- Row -->


<!--

<font color=brown>
<b><font size=5>Source Code</font></b><br>
</font>
<br>

<center>
<table border=0>
<tr>
<td><a href="christmas/2008/source/main.c.txt">main.c</a></td>
<td><a href="christmas/2008/source/bushes.c.txt">bushes.c</a></td>
</tr><tr>
<td><a href="christmas/2008/source/Makefile.txt">Makefile</a></td>
<td><a href="christmas/2008/source/sign.c.txt">sign.c</a></td>
</tr><tr>
<td><a href="christmas/2008/source/main.h.txt">main.h</a></td>
<td><a href="christmas/2008/source/snowmen.c.txt">snowmen.c</a></td>
</tr><tr>
<td><a href="christmas/2008/source/clock.c.txt">clock.c</a></td>
</tr><tr>
<td><a href="christmas/2008/source/lor.c.txt">lor.c</a></td>
<td><a href="christmas/2008/source/lor.h.txt">lor.h</a></td>
</tr><tr>
<td><a href="christmas/2008/source/320controller.c.txt">320controller.c</a></td>
<td><a href="christmas/2008/source/320controller.h.txt">320controller.h</a></td>
</tr>
</table>
</center>

-->

<br><br>
</center>

<?php include "footer.phtml" ?>

