<?php 
$title="Christmas 2014 at the Hormanns";
$subTitle="Christmas 2014";
include "intro.phtml" ?>

<div class="container-fluid"><!--Main Container -->

<center>
<?php Christmas_years(); ?>
</center>
<div class="row">
<div class="col-sm-8">
<h1>Christmas 2014 at the Hormann's</h1>

2014 was our forthteenth year for an animated Christmas display.  This year there were a number of changes.  The biggest was the addtion of the scrolling Grid below the countdown clock.  This is created using nearly 1,000 indiviually controlled RGB pixals and some clever programming. Also red/green/blue flood lights that shine up on the house were replaced with 4 hand build RGB lamps. These do a much better job with color mixing. <br><br>

Behind the scenes, a number of other changes were done.  All of the old C code (some dating back to 2001) was replaced with C++ code.  In addtion, the old <a href="parallel320.phtml">320 Parallel Port Controller</a> was finally retired along with the P-500Mhz PC that controls the display.   An old Athlon (yes, we collect old machines) was put into service as well as a new DMX controller (for the spot lights and countdown clock) and a PixLite 4 board to control the Grid below the clock. 7 LOR controllers are also in use. 

<br><br>
For the last 9 years or so, a small (but growing) group of neighbors have
braved the cold to watch the clock hit mid-night and welcome Christmas.  
This year, we had over 20 neighbors come and watch the clock hit zero. Our daugher stayed up and served them hot chocolate.


<br><br>

<h2>Map</h2>
<?php include "christmas/display.phtml" ?>
<h2>Movies</h2>
We are hosting the movies on YouTube again.  If you have problems 
accessing them, please let us know.  They should show up below. <i>Note that 
all are available in HD. </i>

<br><br>
<center>

<?php 
   $movies = array("BrFh89OS9Ys", "YY1jnphglgw", "RfnnOA3iYeo", "tCQ9uxtrXfQ",  "pv7CyPR6O50");

   foreach ($movies as $mov)
   {
      echo("<a href=\"https://www.youtube.com/watch?v=$mov\">");
      echo("<img src=\"https://img.youtube.com/vi/$mov/0.jpg\" ");
      echo("style=\"border-style:none; margin: 5px 5px 5px 5px; height:250px\">" );
      echo("</a>");
   }
?>


</center>

<br><br>


<h2>Statistics</h2>
<ul>
<li> ~13,000 lights + ~1,100 RGB Lights
<li> 48 LOR Circuits + 3049 DMX Circuits
<li> ~2000 ft electrical and control Wire
</ul>

<h2>Pictures</h2>
<font size=-2 color="brown">(Click image to enlarge)</font>
<br>

<div class="old-picture">

<a href="christmas/2014/Tree2_640.png">
<img src="christmas/2014/Tree2_640.png" height=150 ></a>
<a href="christmas/2014/Purple2_640.png">
<img src="christmas/2014/Purple2_640.png" height=150 ></a>

<a href="christmas/2004/Outside/normal_size/IMG_5997.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_5997.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_5999.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_5999.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_6000.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6000.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_6001.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6001.JPG ></a>

<a href="christmas/2004/Outside/normal_size/IMG_6209.JPG">
<img src=christmas/2004/Outside/thumbnails/IMG_6209.JPG ></a>
</div>
<br><br><br>


<font color=brown>
<b><font size=5>Source Code</font></b><br>
</font>
<br>

All of the source code used in the display is licensed under the GPLv3 and published on 
<a href = "https://bitbucket.org/ghormann/gregslights">Bitbucket</a>.


</div><!--sm-8-->
<div class="col-sm-4">
<?php include "favDisplays.phtml" ?>
</div><!-- Sm-4 -->
</div><!-- Row -->



<?php include "footer.phtml" ?>

