<?php

class ChristmasPage
{
   public function render() {
     global $title;

     echo("<h1>$title</h1>");
     echo "<center>\n";
     Christmas_years();
     echo "</center>\n";
     $this->intro();

     echo("<h2>Movies</h2>");
     youtubeVideo($this->getMovies());

     echo("<h2>Statistics</h2>");
     $this->stats();

     echo("<br><br><h2><a name=\"house_address\">Location</a></h2>");
     include "christmas/display.phtml";

   }
   
   public function intro()
   {
      echo("Override me");
   }

   public function getMovies() {
      return array();
   }

   public function stats()
   {
      // Override me
   }

}

?>
