<?php 
$title="Christmas 2001 at the Hormanns";
$subTitle="Christmas 2001";
include "intro.phtml" ?>


<div class="row">
<div class="col-sm-8">
<h1>Christmas 2001 at the Hormanns</h1>
<center>
<?php Christmas_years(); ?>
</center>


<!--############## Start left body of table #########-->

2001 was the first year we put up an animated (computer controlled)
display.  All animated lights were by controlled 16 circuits via my 
<a href="parallel_boxes.phtml">original parallel port 
control box</a>.  This was also the first year for the new house!

<p>

<iframe src="https://www.youtube.com/embed/N65CUHeHlCc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe src="https://www.youtube.com/embed/G7D2qBwhOCE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>

<h2>The Layout</h2>
<ul>
<li style="padding-bottom: 8px">
    The <a href="/new/images/star.jpg">
    Star</a> took its position in the window above the door.

<li style="padding-bottom: 8px">
     Red rope lights was be run down the edge of the drive way. (Always on)

<li style="padding-bottom: 8px"> 
     In the edge of the yard (left when facing the road) a "Merry
     Christmas" sign sitting just off the ground at a 90 degree angle to the
     road.  The sign was about 1 foot tall and made of lights. 

<li style="padding-bottom: 8px"> 
     The bushes were be divided into three groups with each group being
     wired across the main door.  (ie, the two spiral bushes on each side of
     the door were a group, and then the next couple of outer bushes to
     each side of the door were another group, etc.) Each group could be 
     either red, blue, or green (or a mixture of the three). 3*3 = 9 circuits.
    

<li style="padding-bottom: 8px"> 
     One circuit was configured to light up all white lights in the bushes.
     

<li style="padding-bottom: 8px">  
     White icicle lights were mounted in the gutters. These were on a 
     switchable circuit.
     

<li style="padding-bottom: 8px"> 
     Each of the 5 windows on the top floor were outlined in rope light,
     each on its own individual circuit.

</ul>


</div><!--sm-8-->
<div class="col-sm-4" style="text-align:center;">
<!--############# End left body of table ##########-->
<a href="/new/images/devon/front1.jpg">
<figure>
<img src = "/new/images/devon/_front1.jpg" width=174 
            height=116 border=0>
<figcaption style="text-align:center"><font size = "-2"> Full Size</font></figcaption>
</figure>
</a>

<br><br><br>

<a href="/new/images/devon/front2.jpg">
<img src = "/new/images/devon/_front2.jpg" width=174 
            height=116 border=0>
<center><font size = "-2"> Full Size</font></center></a>
</div><!--sm-4-->
</div><!-- row -->

<!-- ############## Start row Two ################-->
<div class="row">
<div class="col-sm-8">
<h2>The Patterns</h2>
<ul>
<li style="padding-bottom: 8px"> 
     <u>Scrolling Bushes</u>: Bushes scroll inwards using different colors

<li style="padding-bottom: 8px"> 
     <u>Dancing bushes</u>: Bushes change colors outwards using Green, Red,
     Blue, Green-Blue, Green-Red, Red-Blue, and Red-Green-Blue.

<li style="padding-bottom: 8px"> 
     <u>Window Dance</u>: The 5 windows do a back and forth pattern as the 
     pattern gets faster and faster.

<li style="padding-bottom: 8px"> <u>White flash</u>: The bushes and windows/icicle lights flash back and 
     forth faster and faster.

</ul>

</div><!--sm-8-->
<!-- ############## Row Two picture ################-->
<div class="col-sm-4">
<a href="http://www.planetchristmas.com">Planetchristmas.com</a><br>
<a href="http://www.cooldisplays.net">CoolDisplays.net</a><br>
</div><!--sm-4-->
</div><!-- row -->

<!-- ############### Added Row #################-->
<div class="row">
<div class="col-sm-8">

<!--
<h2>The Movies - Low Res</h2>
<ul>
<li><a href="christmas/2001/disp_picts/show.rm">Much of the Show </a> 10.0Meg (Real Video) 3:45 Min
<li><a href="christmas/2001/disp_picts/behind.rm">Behind the Scenes </a> 6.0Meg (Real Video) 3:10 Min
</ul>

-->

<h2>The Movies - High Res</h2>
<ul>
<li><a href="christmas/2001/disp_picts/bushes.MPG">Moving Bushes</a>   1.3Meg (MPEG) 15 sec
<li><a href="christmas/2001/disp_picts/sliding_bushes.MPG">Sliding Bushes</a>  1.3Meg (MPEG) 15 sec
<li><a href="christmas/2001/disp_picts/whole_yard.MPG">Whole Yard</a>  1.3Meg (MPEG) 15 sec
<li><a href="christmas/2001/disp_picts/window_dance2.MPG">Window Dance</a>  1.3Meg (MPEG) 15 sec

</ul>

</div><!-- sm-8 -->

<!-- ################ Picture for added row -->

<div class="col-sm-4">
<img src="images/video.gif" width=52 height=58>
</div><!--sm-4-->
</div><!-- row -->

<!-- ############## Start row Three ################-->
<h2>The Pictures</h2>
<font size=-2 color="brown">(Click image to enlarge)</font>
<br>

<div class="old-picture">
<A href="christmas/2001/disp_picts/all_green.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_all_green.jpg" border="1" alt="_all_green.jpg"></A>
<A href="christmas/2001/disp_picts/all_multi1.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_all_multi1.jpg" border="1" alt="_all_multi1.jpg"></A>
<A href="christmas/2001/disp_picts/all_multi2.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_all_multi2.jpg" border="1" alt="_all_multi2.jpg"></A>
<A href="christmas/2001/disp_picts/four_windows.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_four_windows.jpg" border="1" alt="_four_windows.jpg"></A>


<A href="christmas/2001/disp_picts/all_multi3.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_all_multi3.jpg" border="1" alt="_all_multi3.jpg"></A>
<A href="christmas/2001/disp_picts/all_red.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_all_red.jpg" border="1" alt="_all_red.jpg"></A>
<A href="christmas/2001/disp_picts/all_white.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_all_white.jpg" border="1" alt="_all_white.jpg"></A>
<A href="christmas/2001/disp_picts/one_window.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_one_window.jpg" border="1" alt="_one_window.jpg"></A>

<A href=images/star.jpg>
<IMG width=174 height=131 SRC="images/_star.jpg" border="1" alt="star.jpg"></A>
<A href="christmas/2001/disp_picts/bushes_only.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_bushes_only.jpg" border="1" alt="_bushes_only.jpg"></A>
<A href="christmas/2001/disp_picts/bushes1.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_bushes1.jpg" border="1" alt="_bushes1.jpg"></A>
<A href="christmas/2001/disp_picts/green_middle.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_green_middle.jpg" border="1" alt="_green_middle.jpg"></A>


<A href="christmas/2001/disp_picts/star2001.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_star2001.jpg" border="1" alt="_star2001.jpg"></A>
<A href="christmas/2001/disp_picts/merry_christmas.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_merry_christmas.jpg" border="1" alt="_merry_christmas.jpg"></A>
<A href="christmas/2001/disp_picts/whole_1.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_whole_1.jpg" border="1" alt="_whole_1.jpg"></A>
<A href="christmas/2001/disp_picts/start_red.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_start_red.jpg" border="1" alt="_start_red.jpg"></A>

</div>

<h2>Behind the Scenes</h2>


<A href="christmas/2001/disp_picts/boxes_hooked_up.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_boxes_hooked_up.jpg" border="1" alt="_boxes_hooked_up.jpg"></A>
<A href="christmas/2001/disp_picts/computer.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_computer.jpg" border="1" alt="computer.jpg"></A>
<A href="christmas/2001/disp_picts/cord1.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_cord1.jpg" border="1" alt="_cord1.jpg"></A>
<A href="christmas/2001/disp_picts/cord2.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_cord2.jpg" border="1" alt="_cord2.jpg"></A>

<A href="christmas/2001/disp_picts/cord3.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_cord3.jpg" border="1" alt="_cord3.jpg"></A>
<A href="christmas/2001/disp_picts/cord4.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_cord4.jpg" border="1" alt="_cord4.jpg"></A>
<A href="christmas/2001/disp_picts/cord5.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_cord5.jpg" border="1" alt="_cord5.jpg"></A>
<A href="christmas/2001/disp_picts/cord6.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_cord6.jpg" border="1" alt="_cord6.jpg"></A>

<A href="christmas/2001/disp_picts/four_strand.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_four_strand.jpg" border="1" alt="_four_strand.jpg"></A>
<A href="christmas/2001/disp_picts/sign.jpg">
<IMG width=174 height=131 SRC="christmas/2001/disp_picts/_sign.jpg" border="1" alt="_sing.jpg"></A>

<h2>Statistics</h2>

<ul>
<li> 4000+ mini lights in the bushes
<li> 300 mini lights in the Merry Christmas sign
<li> 90 Feet of white rope light
<li> 72 Feet of Red rope light
<li> 500 icicle lights
<li> P-75 Mhz PC
<li> 16 circuits controlled by two 
     <a href="parallel_boxes.phtml"> parallel boxes</a>
<li> 1720 ft of extension cord.
   
</ul>

<?php include "footer.phtml" ?>
