<?php 
$title="Christmas 2002 at the Hormanns";
$subTitle="Christmas 2002";
include "intro.phtml" ?>

<div class="container-fluid"><!--Main Container -->

<center>
<?php Christmas_years(); ?>
</center>

<div class="row">
<div class="col-sm-8">
<h1>Christmas 2002 at the Hormanns</h1>

This is our second year for an animated Christmas display.  This year a lot 
of time and money was spent on controller hardware. The switch over to the new 
<a href="parallel320.phtml">320 Circuit Controller</a> was more timing 
consuming then planned, but this will give us the capacity to add a lot
more lights in the future. <br><br>


<font size=5><b>
<center> See the story about our display on 
<a href="http://aroundcinci.com/gen_includes/article.asp?articleid=760&subName=&catName=Community">AroundCinci.com</a>
</center>

</b></font>
<br><br>

This year we added the "count down clock" as well as the snowmen.  
The clock has been more popular than expected  (which is good because it is 
more complex then viewers probably realize.)  I got the idea of the clock
(which counts down the number of seconds until Christmas) from a co-worker.
It works simular to a standard digital clock radio.  Each of the 7 digits is made 
up of seven segments. By lighting up different subsets of segments, all 
10 digits (0-9) can be produced. Sounds simple, but this means that 49
circuits had to be build as well as 49 strands of lights hung in the 
correct alignment to produce the effect.

<br><br>
The snowmen were a little easier to construct (though I wish I had done it 
differently because the wires that should be hidden tend to show.) The 
snow men only require 16 circuits and produces "animation" by lighting up 
different sets of lights (that represent different arm and snow ball positions)
in specific orders. This is a modified version of Drew Heckman's design.
<br><br><br>

<h2>Movies</h2>

<div class="container">
   <div class="row">
      <div class="col-6 col-md-4">
         <img src="christmas/2002/_2002_clock369.jpg"> <br>
         Clock (<a href="christmas/2002/movies/clock.wmv">WMV</a>)
           (<a href="christmas/2002/movies/clock.rm">Real</a>) (1Mb)
      </div>

      <div class="col-6 col-md-4">
         <img src="christmas/2002/_2002_house_close_1.jpg"> <br>
         Clock (<a href="christmas/2002/movies/bushes_light.wmv">WMV</a>)
           (<a href="christmas/2002/movies/bushes_light.rm">Real</a>) (4Mb)
      </div>

      <div class="col-6 col-md-4">
         <img src="christmas/2002/_2002_snowman_4.jpg"><br>
         Snowmen (<a href="https://www.youtube.com/watch?v=1nC7ShJl3tU">Youtube</a>)
             (<a href="christmas/2002/movies/snowmen.rm">Real</a>) (4Mb)
      </div>
   </div><!-- Row -->
</div><!-- container-->


<h2>Statistics</h2>
<ul>
<li> ~6000 lights
<li> 84 Circuits
<li> ~2000 ft Wire
<li> P-75 Mhz PC
</ul>
</div><!--sm-8-->
<div class="col-sm-4">
<?php include "favDisplays.phtml" ?>
</div><!-- Sm-4 -->
</div><!-- row -->

<h2>Pictures</h2>
<font size=-2 color="brown">(Click image to enlarge)</font>
<br>

<a href="christmas/2002/2002_clock349.jpg">
	<IMG SRC="christmas/2002/_2002_clock349.jpg" border="1" alt="2002_clock349.jpg">
</a>
<a href="christmas/2002/2002_clock364.jpg">
	<IMG SRC="christmas/2002/_2002_clock364.jpg" border="1" alt="2002_clock364.jpg">
</a>
<a href="christmas/2002/2002_clock369.jpg">
	<IMG SRC="christmas/2002/_2002_clock369.jpg" border="1" alt="2002_clock369.jpg">
</a>
<a href="christmas/2002/2002_house_close_1.jpg">
	<IMG SRC="christmas/2002/_2002_house_close_1.jpg" border="1" alt="2002_house_close_1.jpg">
</a>
<a href="christmas/2002/2002_snowman_3.jpg">
	<IMG SRC="christmas/2002/_2002_snowman_3.jpg" border="1" alt="2002_snowman_3.jpg">
</a>
<a href="christmas/2002/2002_snowman_4.jpg">
	<IMG SRC="christmas/2002/_2002_snowman_4.jpg" border="1" alt="2002_snowman_4.jpg">
</a>
<a href="christmas/2002/2002_snowman_5.jpg">
	<IMG SRC="christmas/2002/_2002_snowman_5.jpg" border="1" alt="2002_snowman_5.jpg">
</a>
<a href="christmas/2002/2002_snowman_6.jpg">
	<IMG SRC="christmas/2002/_2002_snowman_6.jpg" border="1" alt="2002_snowman_6.jpg">
</a>
<a href="christmas/2002/bushes_n1.jpg">
	<IMG SRC="christmas/2002/_bushes_n1.jpg" border="1" alt="bushes_n1.jpg">
</a>
<a href="christmas/2002/bushes_n2.jpg">
	<IMG SRC="christmas/2002/_bushes_n2.jpg" border="1" alt="bushes_n2.jpg">
</a>
<a href="christmas/2002/bushes_n3.jpg">
	<IMG SRC="christmas/2002/_bushes_n3.jpg" border="1" alt="bushes_n3.jpg">
</a>
<a href="christmas/2002/bushes_n4.jpg">
	<IMG SRC="christmas/2002/_bushes_n4.jpg" border="1" alt="bushes_n4.jpg">
</a>
<a href="christmas/2002/computer_ports.jpg">
	<IMG SRC="christmas/2002/_computer_ports.jpg" border="1" alt="computer_ports.jpg">
</a>
<a href="christmas/2002/floods_both.jpg">
	<IMG SRC="christmas/2002/_floods_both.jpg" border="1" alt="floods_both.jpg">
</a>

<br><br><br>


<h2>Behind the Scenes</h2>
<font size=-2 color="brown">(Click image to enlarge)</font>
<br>

<a href="christmas/2002/2002_board1.jpg">
	<IMG SRC="christmas/2002/_2002_board1.jpg" border="1" alt="2002_board1.jpg">
</a>
<a href="christmas/2002/2002_board2.jpg">
	<IMG SRC="christmas/2002/_2002_board2.jpg" border="1" alt="2002_board2.jpg">
</a>
<a href="christmas/2002/2002_board_3.jpg">
	<IMG SRC="christmas/2002/_2002_board_3.jpg" border="1" alt="2002_board_3.jpg">
</a>

<a href="christmas/2002/2002_computer_1.jpg">
	<IMG SRC="christmas/2002/_2002_computer_1.jpg" border="1" alt="2002_computer_1.jpg">
</a>
<a href="christmas/2002/2002_computer_2.jpg">
	<IMG SRC="christmas/2002/_2002_computer_2.jpg" border="1" alt="2002_computer_2.jpg">
</a>
<a href="christmas/2002/2002_computer_3.jpg">
	<IMG SRC="christmas/2002/_2002_computer_3.jpg" border="1" alt="2002_computer_3.jpg">
</a>
<a href="christmas/2002/2002_computer_4.jpg">
	<IMG SRC="christmas/2002/_2002_computer_4.jpg" border="1" alt="2002_computer_4.jpg">
</a>

<a href="christmas/2002/2002_connector.jpg">
	<IMG SRC="christmas/2002/_2002_connector.jpg" border="1" alt="2002_connector.jpg">
</a>
<a href="christmas/2002/wire_connectors.jpg">
	<IMG SRC="christmas/2002/_wire_connectors.jpg" border="1" alt="wire_connectors.jpg">
</a>
<a href="christmas/2002/wires_2.jpg">
	<IMG SRC="christmas/2002/_wires_2.jpg" border="1" alt="wires_2.jpg">
</a>

<a href="christmas/2002/2002_wires_1.jpg">
	<IMG SRC="christmas/2002/_2002_wires_1.jpg" border="1" alt="2002_wires_1.jpg">
</a>
<a href="christmas/2002/box_closed_1.jpg">
	<IMG SRC="christmas/2002/_box_closed_1.jpg" border="1" alt="box_closed_1.jpg">
</a>
<a href="christmas/2002/box_closed_2.jpg">
	<IMG SRC="christmas/2002/_box_closed_2.jpg" border="1" alt="box_closed_2.jpg">
</a>
<a href="christmas/2002/box_closed_3.jpg">
	<IMG SRC="christmas/2002/_box_closed_3.jpg" border="1" alt="box_closed_3.jpg">
</a>
<a href="christmas/2002/box_open_1.jpg">
	<IMG SRC="christmas/2002/_box_open_1.jpg" border="1" alt="box_open_1.jpg">
</a>
<a href="christmas/2002/box_open_2.jpg">
	<IMG SRC="christmas/2002/_box_open_2.jpg" border="1" alt="box_open_2.jpg">
</a>
<a href="christmas/2002/2002_box_1.jpg">
	<IMG SRC="christmas/2002/_2002_box_1.jpg" border="1" alt="2002_box_1.jpg">
</a>
<a href="christmas/2002/2002_box_2.jpg">
	<IMG SRC="christmas/2002/_2002_box_2.jpg" border="1" alt="2002_box_2.jpg">
</a>
<a href="christmas/2002/2002_box_3.jpg">
	<IMG SRC="christmas/2002/_2002_box_3.jpg" border="1" alt="2002_box_3.jpg">
</a>


<br><br><br>


<h2>Source Code</h2>
The following source code controlled this year's display from a P-75
running the FreeBSD 4.7 OS.
<br> <br><br>

<center>
<table border = 0 cellpadding=20>
<tr>
  <td>
	<a href="christmas/2002/source/Makefile.txt">Makefile</a> <br>
	<a href="christmas/2002/source/main.c.txt">Main.c</a> <br>
	<a href="christmas/2002/source/2002.h.txt">2002.h</a> <br>
	<a href="christmas/2002/source/320controller.h.txt">320controller.h</a> <br>
  <td>
	<a href="christmas/2002/source/320controller.c.txt">320controller.c</a> <br>
	<a href="christmas/2002/source/bushes.c.txt">bushes.c</a> <br>
	<a href="christmas/2002/source/sign.c.txt">sign.c</a> <br>
	<a href="christmas/2002/source/snowmen.c.txt">snowmen.c</a> <br>
</tr>
</table>
</center>

</div> <!-- center -->

<?php include "footer.phtml" ?>
