<?php 
$title="Christmas 2022 at the Hormanns";
$subTitle="Christmas 2022";
include "intro.phtml" ?>

<?php
require_once 'christmasBase.phtml';

class Page extends ChristmasPage
{
   public function intro()
   {

?>

<br><br>
2022 was our 22th year for an animated Christmas Lights Display. Construction started November 10th and we went live November 23rd.
This year we added the tunnel on the right and move the countdown clock to the left of the display.  We had about 20 individuals join
us to see the countdown clock hit zero. (It was bitter cold!) 

<p>

<?php 
   } // body

   public function getMovies()
   {

   $movies = array(
             array("glANXkb4Blc", "The Tunnel"),
             array("yYflTRQp4Bg", "You make it feel like Christmas"),
             array("dYW9W9nW_WM", "Christmas Can Can"),
             array("lpEr2uWw1Hs", "Ditto Sign"),
             array("PweKc7Nfiqk", "Christtmas Eve Count Down"),
             array("ZqcX-DwMBcQ", "I Got The Joy (Go Fish)"),
             array("9NDDn_jIQes", "The Peanuts"),
             array("z1BwxrdscaA", "Hot Chocolate from Polar Express"),
             array("0VWZ2PcjoME", "Here comes Santa Claus"),
             array("Bp_bAw_6luI", "Christmas Everyday (Simple Plan)"),
             array("owQQIQTuKWU", "The Grinch"),
             array("WNX7di7yUOI", "12 Days of Christmas (Drone)"),
             array("qKlvn1HOvPs", "Christmas Cannon (Drone)"),
             array("RAzyyV-Gtpo", "EDM Carol of the Bells (Sauniks)"),
             array("4gOUaJnbIuo", "I Want a Hippopotamus for Christmas"),
             array("FqKw8tO_xlY", "House on Christmas Street"),
             array("JrzXrnm8E5M", "Donation Reminder"),
             array("plRMYxv636g", "Light of Christmas"),
             array("KhODj5q_kz0", "Jingle Dogs (Drone)"),
             array("nGgtz1Q6uZI", "I heard the bells on Christmas Day"),
             array("1olzWXzyysY", "Little Drummer Boy"),
             array("Z-uH736zc94", "Amazing Grace (Drone)"),
             array("OC9ok86wrYI", "Sugar Plum Fairy"),
             array("k8twoPfAkWc", "Joy to the World"),
             array("t5KOCj1krJw", "Christmas Minions"),
             array("kmifjoyrMbQ", "Happy Birthday"),
             array("5XhNOP-Emk4", "Setup: Day 9 - Arches and Bushes"),
             array("kRlAkqckKcA", "Setup: Day 6 - Be carefull with tools"),
             array("Y9B1HtF38_4", "Setup: Day 5 - Ground Elements"),
             array("-Vu7cgyY8yI", "Setup: Day 4 - Snowmen"),
             array("x4E47dOONRg", "Setup: Day 3 - Outline and Megatrees"),
             array("5TOqnxBzl0U", "Setup: Day 2 - House Outline and Windows"),
             array("sZJri6YLVUI", "Setup: Day 1 - The Grid"),
   );

   return $movies;
   }

   public function stats()
   {

?>

<ul>
<li> 64,289 "Smart" RGB lights that can be set to any color individually
<li> 880 "Dumb" RGB light bulbs (20 in each of the Stars on the ground)
<li> 87 P10 panels in the sign above the Garage door (equivalent of 27,840 pixels)
<li> 11 Pixel Controllers (AlphaPix 4 + Falcon16v3, Kulp K8-B, Kulp K16)
<li> 5 "Dumb" RGB Controllers (Stars in yard)
<li> 63 DC Power Supplies
<li> 1 Raspberry Pi running FPP to control the show
<li> 4 Beagle Bone Black running FPP to control the P10s and some pixels
<li> 2 Virtual Machines to handle interactive elements of display
<li> Too many electrical and control wire to count
</ul>



<?php 
   } //stats
} // class

$me = new Page();
$me->render();

include "footer.phtml" ?>

