<?php 
$title="Christmas 2020 at the Hormanns";
$subTitle="Christmas 2020";
include "intro.phtml" ?>

<?php
require_once 'christmasBase.phtml';

class Page extends ChristmasPage
{
   public function intro()
   {

?>

2020 was our 20th year for an animated Christmas Lights Display. This year we added five new songs, the ability to vote for the type of <a href="snowmen.php">snowmen</a>, and the <a href="christmas_info_board.phtml">new sign above the garage door</a> that displays the radio station and power being consumed by the display.

<br><br>
For the last fifteen years or so, a number of neighbors have braved the cold to watch the clock hit midnight and welcome Christmas (<a href="https://youtu.be/KzlcXVM5kTE">2019 Video</a>). 


We hope you'll join us this year.  If you are not sure where we are located, we have a nice <a href="christmas.phtml">map available</a>.

<!--
This year was amazing with over 45 neighbors joining to celebrate as the clock hit zero. Hopefully you'll join us next year!
-->

<p>

<?php 
   } // body

   public function getMovies()
   {

   $movies = array(
             array("ZqcX-DwMBcQ", "I Got The Joy (Go Fish)"),
             array("ImTdbdrqfok", "Hot Chocolate from Polar Express"),
             array("Bp_bAw_6luI", "Christmas Everyday (Simple Plan)"),
             array("owQQIQTuKWU", "The Grinch"),
             array("KaPiWEdYy0o", "The Peanuts"),
             array("WNX7di7yUOI", "12 Days of Christmas (Drone)"),
             array("qKlvn1HOvPs", "Christmas Cannon (Drone)"),
             array("RAzyyV-Gtpo", "EDM Carol of the Bells (Sauniks)"),
             array("4gOUaJnbIuo", "I Want a Hippopotamus for Christmas"),
             array("FqKw8tO_xlY", "House on Christmas Street"),
             array("plRMYxv636g", "Light of Christmas"),
             array("KhODj5q_kz0", "Jingle Dogs (Drone)"),
             array("nGgtz1Q6uZI", "I heard the bells on Christmas Day"),
             array("bkg0-Q3mMzU", "Little Drummer Boy"),
             array("Z-uH736zc94", "Amazing Grace (Drone)"),
             array("OC9ok86wrYI", "Sugar Plum Fairy"),
             array("k8twoPfAkWc", "Joy to the World"),
             array("t5KOCj1krJw", "Christmas Minions"),
             array("oEVqY96ajgQ", "Here comes Santa Claus"),
             array("GPOL_nibIAU", "Digital Snowmen"),
             array("66iHa96EXFY", "Setting Up: Day 1"),
             array("a73GRbzLz6g", "Setting Up: Day 2"),
             array("unpOYCNJzlE", "Setting Up: Day 4"),
             array("9xToVesowGE", "Setting Up: Day 5"),
             array("SNr1QC-ey9Y", "Setting Up: Day 6"),
             array("3k3gA-uyuZc", "Setting Up: Day 7"),
             array("es61nZn9HGA", "Setting Up: Day 8"),
   );

   return $movies;
   }

   public function stats()
   {

?>
<ul>
<li> 41,535 "Smart" RGB lights that can be set to any color individually
<li> 880 "Dumb" RGB light bulbs (20 in each of the Stars on the ground)
<li> 33 P10 pannels in the sign above the Garage door (equilivant of 10,560 pixels)
<li> 11 Pixel Controllers (AlphaPix 4 + Falcon16v3)
<li> 5 "Dumb" RGB Controllers (Stars in yard)
<li> 61 DC Power Supplies
<li> 1 Raspberry Pi running FPP to control the show
<li> 1 Beagle Bone Black running FPP to control the Board above the Garage
<li> 2 Virtual Machines to handle interative elements of display
<li> Too many electrical and control wire to count
</ul>



<?php 
   } //stats
} // class

$me = new Page();
$me->render();

include "footer.phtml" ?>

