<?php 
$title="Christmas 2019 at the Hormanns";
$subTitle="Christmas 2019";
include "intro.phtml" ?>

<?php
require_once 'christmasBase.phtml';

class Page extends ChristmasPage
{
   public function intro()
   {

?>

2019 is our ninetieth year for an animated Christmas Lights Display. This year we added high-def grids to the windows, a second mega tree, and compeltly rebuilt the <a href="snowmen.php">the showmen</a>. In addition, we added a feature where viewers could <a href="voting.phtml">vote for the next song</a> to be played.

<br><br>
For the last fourteen years or so, a number of neighbors have braved the cold to watch the clock hit midnight and welcome Christmas. (<a href="https://youtu.be/KzlcXVM5kTE">2019 Video</a>)


<!--
We hope you'll join us this year.
-->

This year was amazing with over 45 neighbors joining to celebrate as the clock hit zero. Hopefully you'll join us next year!

<?php 
   } // body

   public function getMovies()
   {

   $movies = array(
             array("WNX7di7yUOI", "12 Days of Christmas (Drone)"),
             array("qKlvn1HOvPs", "Christmas Cannon (Drone)"),
             array("RAzyyV-Gtpo", "EDM Carol of the Bells (Sauniks)"),
             array("4gOUaJnbIuo", "I Want a Hippopotamus for Christmas"),
             array("FqKw8tO_xlY", "House on Christmas Street"),
             array("plRMYxv636g", "Light of Christmas"),
             array("qqzKwR5QexM", "12 Days of Christmas"),
             array("6jinXp_qiac", "Jingle Dogs"),
             array("KhODj5q_kz0", "Jingle Dogs (Drone)"),
             array("nGgtz1Q6uZI", "I heard the bells on Christmas Day"),
             array("bkg0-Q3mMzU", "Little Drummer Boy"),
             array("CZtOr_h6B8M", "Amazing Grace"),
             array("Z-uH736zc94", "Amazing Grace (Drone)"),
             array("OC9ok86wrYI", "Sugar Plum Fairy"),
             array("k8twoPfAkWc", "Joy to the World"),
             array("t5KOCj1krJw", "Christmas Minions"),
             array("oEVqY96ajgQ", "Here comes Santa Claus"),
             array("T_gxEN5Hek8", "Christmas Cannon"),
             array("GPOL_nibIAU", "Digital Snowmen"),
             array("KzlcXVM5kTE", "Clock Hitting zero"),
             array("ZMBEbfsgzBY", "Behind the Scenes")
   );

   return $movies;
   }

   public function stats()
   {

?>
<ul>
<li> 41,535 "Smart" RGB lights that can be set to any color individually.
<li> 880 "Dumb" RGB light bulbs (20 in each of the Stars on the ground.)
<li> 11 Pixel Controllers (AlphaPix 4 + Falcon16)
<li> 5 "Dumb" RGB Controllers (Stars in yard.)
<li> 60 DC Power Supplies
<li> Too many electrical and control wire to count
</ul>



<?php 
   } //stats
} // class

$me = new Page();
$me->render();

include "footer.phtml" ?>

