

<!-- NOTE: This page was auto genreated by genereate.pl. Do not directly EDIT-->




<HTML><HEAD>
<style>
.heading { font-style: Italic; 
              font-size: 24px;
	      text-decoration: none;
	      color: blue;}

.outline { border-style: dotted; 
           border-color: blue; }

.code { color: blue; }

</style>

<link rel="stylesheet" href="menu/menu1.css">
<script language="JavaScript" src="menu/menu.js"></script>
<script language="JavaScript" src="menu/menu_items.js"></script>
<script language="JavaScript" src="menu/menu_tpl1.js"></script>
</HEAD>


<TITLE>Our Home Page</TITLE></HEAD>
<body bgcolor="#F8F5D6">


<center>
<font color=brown>
<h1>Greg's Schedule</h1>
</font>
</center>

<font face="Arial, Geneva">
<center>

<br><br><br>

<noscript>
<center>

<table border=0>
<tr>
<td valign="top">
<ul>
<li> <a href="home.phtml">Home Page</a>
<li> <a href="greg.phtml">Greg's Page</a>
<li> <a href="mary.phtml">Mary's Page</a>
<li> <a href="pictures.phtml">Some Pictures</a>
</ul>
</td>
<td valign="top">
<ul>
<li> <a href="christmas.phtml">Christmas</a>
   <ul>
   <li><a href="christmas2001.phtml">2001 Display</a>
   <li><a href="christmas2002.phtml">2002 Display</a>
   <li><a href="christmas2003.phtml">2003 Display</a>
   <li><a href="christmas2004.phtml">2004-2007 Display</a>
   <li><a href="christmas2008.phtml">2008 Display</a>
   <li><a href="parallel_boxes.phtml">8 circuit 
                   control box</a>
   <li><a href="parallel320.phtml">320 circuit 
                   control box</a>
   </UL>
</UL>
</td>
</tr>
</table>

</center>
</noscript>

</center>



<br>

<hr><br>
<center>


<table border = 0><tr><td>
<ul>
	<li><a href = "http://www.indiana.edu/~buss205/ert/s205.html">
	BUS S205</a> - Visual Basic
        
	<li><a href = "http://www.cs.indiana.edu/classes/p465">
	CSCI P465</a> - Software Eng. for Information Systems
        
	<li><a href = "http://www.cs.indiana.edu/classes/b538/b538.html">
	CSCI B438</a> - Fundamentals of Computer Networks 
        
	<li>HYPR E317 - Advanced Scuba

	<li>HYPR R322 - Scientific Diver
</ul>
</td></tr></table>
</center>
<p>

<center>
<img src = "/ghormann/new/schedule.phtml?who=greg&name="
height=500 width=500><br><p><br>
This image was created on the fly by <b>Just-In-Time Scheduler</b> written
by <a href = "home.phtml">
Greg Hormann</a>.  

</center>


<hr>
<center>
<table border = 0>
<p>
<tr>

<td>
<a href = "http://www.php.net">
<img src= "images/php.jpg" alt="PHP/FI" width=158 height=50 border=0>
</a>
</td>

<td>
<a href = "http://www.freebsd.org">
<img  src = "images/powerlogo.gif" alt="Powered by FreeBSD" width=171
height=64
border=0>
</a>
</tr>
</table>

<table border=0 width=100% cellspacing=0 cellpadding=5>
<tr>
<td bgcolor="brown" >
<br>
</td>
<td bgcolor="brown"" >
<br>
</td>

</tr>
<tr>
<td>
Greg & Mary Hormann<br>
<a href = "mailto:ghormann@alumni.indiana.edu">ghormann@alumni.indiana.edu</a>
<br>
<a href = "http://www.kconlineinc.com/ghormann/new/home.html">
http://www.kconlineinc.com/ghormann/home.html</a>
</td>
<td align=right>
Copyright &copy 2000-2009<br>
All Rights Reserved
</td>

</tr>

<tr>
<td bgcolor="brown">
<br>
</td>
<td bgcolor="brown">
<br>
</td>
</tr>


</table>
</center>
<font face="Arial, Geneva">

<script language="JavaScript">
var winW = 630, winH = 460;

if (parseInt(navigator.appVersion)>3) {
 if (navigator.appName=="Netscape") {
  winW = window.innerWidth;
  winH = window.innerHeight;
 }
 if (navigator.appName.indexOf("Microsoft")!=-1) {
  winW = document.body.offsetWidth;
  winH = document.body.offsetHeight;
 }
}

MENU_POS1[0]['block_left']= (winW/2) - 180


//document.write(
// "Window width = "+winW+"<br>"
//+"Window height = "+winH+"<br>"
//+"Position = "+MENU_POS1[0]['block_left']
//)


new menu (MENU_ITEMS, MENU_POS1); 
</script>

</body></html>

