<style type="text/css">

.cool-list-displays {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}

.cool-summary {
   border-style: solid;
   border-width: 2px;
}

@media only screen and (min-width: 414px) {
  /* For mobile phones: */
  [class*="cool-summary"] {
      min-width: 380px;
  }
}

@media only screen and (max-width: 354px) {
  /* For mobile phones: */
  [class*="cool-desc-div"] {
      width:100%;
  }
  [class*="cool-summary"] {
      margin-top:15px;
      width:100%;
  }
}

@media only screen and (max-width: 818px) {
  [class*="cool-summary"] {
      border-style: none;
  }
}


</style>
<h3>Our Favorite Light Displays</h3>
   <div id ="favHere"></div>

<script type="text/javascript" src="https://cooldisplays.net/favToolV2.php?u=f2f814292ee8f9276575a81a8d6137e8i2i555fae263f725f3ad15c3a4dfaf7347137805780"> </script>

<script type="text/javascript">
    coolTool.showFav('favHere');
</script>


