<?php 
$title="Greg Hormann";
$subTitle="Meet&nbsp;Greg&nbsp;Hormann";
include "intro.phtml" ?>

<div class="container-fluid"><!--Main Container -->


<center>

<img src = "images/gregshome.gif" alt="Greg Hormann's Home Page"
width=308 height=172><br>
<!--
<p>
<img src = "/new/images/welcome_blink.gif" 
alt="Welcome to my home page!" height=48 width=293>
-->
</center>


<hr>
<p>

<!---#################Start Quick Links################--->

<h1>Greg's Quick Links</h1>

<div class="row">
   <div class="col-sm-auto">
<ul>
<li>Projects:
    <ul>
    <li><a href = "christmas.phtml">
                Computerized Christmas Lights</a>
    <li><a href = "http://www.wawasee-list.net"> The Wawasee List </a>
    <li><a href = "http://www.cooldisplays.net"> 
       CoolDisplays.Net </a>

    <li><a href="https://web.archive.org/web/20040603100149/http://www.dmoz.org/">Open Directory Project</a>
    <li><a href="https://falconchristmas.github.io/">Falcon Pi Player (FPP)</a>

    </ul>
</ul>
<ul>
<li>Other Sites:
   <ul>
   <li><a href="http://www.linkedin.com/in/ghormann">Greg Hormann @ LinkedIn</a>
   <li><a href="http://www.facebook.com/ghormann">Greg Hormann @ Facebook</a>
   </ul>
</ul>
  </div><!--col-->
  <div class="col-sm-auto">

<ul>
<li>Affiliations:
    <ul>
    <li><a href = "http://www.pg.com">Procter & Gamble</a>
    <li><a href = "http://www.indiana.edu">Indiana University</a>
    <li><a href = "http://www.cs.indiana.edu">Indiana University's
        Department of Computer Science</a>
    <li><a href = "http://www.statefarm.com">State Farm Insurance
        </a>(summer intern 1998).
    </ul>
</ul>
</div><!--col-->
</div><!--row-->

<!----#########################End Quick Links###################---->

<hr>
<h1>Meet Greg Hormann</h1>

Well,
After graduating from <a href = "Http://www.indiana.edu">Indiana
University</a> with a <B>BS</B> degree in <a href =
"http://www.cs.indiana.edu">Computer Science</a>, I moved out to
Cincinnati, OH to assume a position with <a href = "Http://www.pg.com">
Procter & Gamble</a>.  After eleven years of support the Pharmaceutical 
Business, I started working for <a href="http://www.wcrx.com">
Warner Chilcott</a> as part of the 
<a href="http://www.bizjournals.com/cincinnati/stories/2009/08/17/daily58.html">P&GP divestiture</a>. But by March, 
<a href ="http://www.wlwt.com/news/22918045/detail.html">
Warner had decided to consolidate</a> its offices in New Jersey.  I did some independent consulting for a few months and then rejoined P&amp;G.

At present, I oversee efforts to adopt addtional Industry 4.0 technology at our Manufacturing sites.

<br><br>

While at IU,
I lived in
<!--
 <a href = 
"http://www.indiana.edu/~iubmap/mapredirect.pl?select=%09BL227%09&Go=Go%21">
Read
Quad</a> 
-->
<a href="http://maps.google.com/maps?hl=en&ie=UTF8&ll=39.1661,-86.514856&spn=0.001892,0.003449&t=h&z=18">Read Quad</a>

(The rent was cheap, I didn't have to cook, and the T-3
connection to the Internet was free!).  Now, I live in

<a href = "http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=Cincinnati,+OH&sll=39.1661,-86.51588&sspn=0.001892,0.003449&ie=UTF8&hq=&hnear=Cincinnati,+Hamilton,+Ohio&t=h&z=11">Cincinnati, OH</a>. 

(The mortgage is expensive, the wife or I have to cook, and
the slower Internet connection cost more than I care to think about!
 -- <i>There are definitely a few things I miss from college</i>.)  

<br><br>

<div class="row">
   <div class="col-sm-2 order-sm-1" style="text-align:center;">
       <img src = "images/freebsd-biglogo.gif" alt = "FREEBSD LOGO" 
class="img-fluid"><br>
   </div>
   <div class="col-sm-8 order-sm-2">
The image on the left is the <a href =
"http://www.freebsd.org">FreeBSD</a> mascot. FreeBSD is a UNIX like operating
system for Intel hardware (much like 
<a href = "http://www.linux.org">Linux</a>).  I have used FreeBSD for over 
20 years on servers at on the home network. 
<a href = "http://riffledev.com/">Jim Riffle</a> turned me on to it. I do also leverage Debian based Linux distrbutions for some projects.
<p>
Yes, 
In case you can't tell by that huge image on the right, I am an
<a href = "http://en.wikipedia.org/wiki/Eagle_Scout_%28Boy_Scouts_of_America%29">
Eagle Scout</a>.  I became an Eagle Scout on March 24, 1994
from <a href="http://nwtroop726.com">Troop 726</a> 
<a href = "http://maps.google.com/maps?client=ubuntu&channel=fs&q=North+Webster,+IN&oe=utf-8&ie=UTF8&hq=&hnear=North+Webster,+Kosciusko,+Indiana&gl=us&ei=D-K-TNLlKIqrnQeG9ZWJDg&ved=0CBYQ8gEwAA&ll=41.325586,-85.69778&spn=0.014664,0.027595&t=h&z=15">
North Webster, IN</a>.  After earning my Eagle, I also spent 3
summers working as an Assistant Scoutmaster.  
   </div><!--col-sm-8-->
   <div class="col-sm-2 order-sm-3" style="text-align:center;">
      <img class="img-fluid" src = "images/eaglebdg.gif" >
   </div>
</div><!--Row-->

<div class="row">
   <div class="col-sm-10 order-sm-1">
As a full time student at <a href = "http://www.indiana.edu/">Indiana
University</a> in <a href = "http://www.iub.edu/">
Bloomington</a>, I completed a <a href =
"http://www.cs.indiana.edu">Computer Science</a> BS degree, a minor in
Mathematics, and a minor in Cognitive Science.  I also worked as an
Undergraduate Teaching Instructor for <a href =
"http://www.cs.indiana.edu/classes/a115">A115: Working the World Wide
Web</a>.  
   </div><!--col-sm-8-->
   <div class="col-sm-2 order-sm-2" style="text-align:center;">
      <img src = "images/IU.gif" ALT="[IU LOGO]" border=0 width=57 height=75 vspace=15 hspace=15>
   </div>
</div><!-- Row-->

<p>

I guess, if you really want to see a <a href = "images/xmas_2003_1.jpg">
picture</a>
of me, you can.  Sorry Girls, I am all ready
taken.  My wife, <a href="mary.phtml">Mary</a>, graduated from IU and now 
is a full time mommy to Emily and Matt.
<p>


That is about I can think of right now, before you leave, be sure to 
 scan over my current projects.  Thanks for 
visiting!
<p>

<hr>
<h1>Projects</h1>

I have just a few big computer related projects going on right now, 

<br><br>

<dl>
<dt><a href = "christmas.phtml">Computer Controlled Christmas Lights</a>
<dd>Lots of my friends think I'm crazy, but I've found a way
to combine two of my favorite hobbies: Outdoor Christmas Lights and 
Computers.
<br><br>
<dt><a href = "http://www.wawasee-list.net">The Wawasee
List</a>
<dd>The Wawasee List contains the names, email addresses, URLs, and
comments about many graduates of Wawasee High School, Syracuse IN. I
founded this list in the fall of 1994 with just 10 entries, it has now
grown to well over 900!  For more information about the list, take the
above link.
<br><br>
<dt><a href = "http://CoolDisplays.net">CoolDisplays.Net</a>
<dd>
A directory for outdoor holiday lighting displays helping visitors find near by holiday displays of interest. This directory works similar to Wiki and should be thought of as a collection of web pages that anyone can edit.
<br><br>
<!--
<dt><a href = "http://www.kconlineinc.com/kclist">KC Online Members List</a>
<dd>This list is very simular to the <a href =
"http://www-wawasee-list.net">Wawasee List</a> (except in
layout).  It allows members of KC Online (a local ISP for Kosciusko
County) to publish their email address, URL, and a little information.

<dt><a href =
"/ghormann/new/schedule.phtml?who=greg&name="> Just-in-time Schedule</a>
<dd>This program takes a <a href =
"/ghormann/new//greg.data">datafile</a> and generates
at load time (on the fly), and image representation of a schedule with the
current time and day highlighted.  (This is many geared for college
students.)
-->
</dl>

<hr>

<?php include "favDisplaysWide.phtml" ?>


<?php include "footer.phtml" ?>
</div><!-- Main Container -->


