<?php 
$title="Mary Hormann";
$subTitle="Meet&nbsp;Mary&nbsp;Hormann";
include "intro.phtml" 
?>

<script type="text/javascript" src="https://cooldisplays.net/tools.php?u=2d1093076abd3bd9d58dd9a3ee698b5ci3idb88fe3e8035e3ed6da0ccd6dbb238cb44f35565"> </script>
<style type="text/css">
img.DisplaySummary {
  width:90px;
  float:left;
  margin:4px;
  border:0px;
}

h1.DisplaySummary {
  margin:5px 0px 0px 0px;
  font-size:20px;
}

table.DisplaySummary {
  margin:0px 0px 0px 0px;
  border-width: 0px;
  border-spacing: 2px;
  border-style: none;
}

td.DisplaySummary {
  border-width: 0px;
  border-spacing: 2px;
  border-style: none;
  vertical-align:text-top;
}

.dispVote {
  color: green;
  font-style:italic;
  font-size: 12px;
}
</style> 

<div class="container-fluid"><!--Main Container -->


<h1>Meet Mary Hormann</h1>

<!--############## Start left body of table #########-->
<div class="row">
<div class="col-sm-8">
One of these days I'll add something, but for now check out my favorite displays at 
<a href="http://cooldisplays.net">CoolDisplays.net</a>.
<br>

<a href="wedding/Honeymoon/mary_hair.jpg">
<img src = "wedding/Honeymoon/_mary_hair.jpg" border=0
            width=135 heigth=174>
</a>

<img src="images/under-construction.gif">
</div><!-- Col 8 -->

<div class="col-sm-4">
<div id ="favHere"></div> 
</div>
</div><!-- Row -->
<?php include "footer.phtml" ?> 


<script type="text/javascript">
    coolTool.showFav('favHere');
</script> 

