

<!-- NOTE: This page was auto genreated by genereate.pl. Do not directly EDIT-->


<html><head>
<title>Resume for Gregory J. Hormann</title>


</head>
<body bgcolor = "#F8F5D6" text = "000000">


<center><font size = 7><strong>
Gregory J. Hormann
</strong></font></center>
<br><br>
<!---
<table width = 100% cellspacing=0 cellpadding=0 >

<tr><th widht=65% align=left>Current Address:</th>
<th width=35% align = left>Permanent Address:</th>
<tr><td>Read-Beck 415</td>		<td>10900 North 500 East</td>
<tr><td>Indiana University</td>		<td>Syracuse, IN 46567</td>
<tr><td>Bloomington, IN 47406</td>	<td>(219)457-3197</td>
<tr><td>(812)857-5796</td>              <td><a href="mailto:ghormann@alumni.indiana.edu">
                                        ghormann@alumni.indiana.edu</a></td>

</table>
--->
<center> <a href="mailto:ghormann@alumni.indiana.edu">ghormann@alumni.indiana.edu</a> </center>
<hr>
<!--		
<center><h1>
<u>Objective</u>
</h1></center>
To secure a challenging position in the computer field involving operating 
systems or information systems with the opportunity for further education.

<BR><BR><BR><BR>
--->



<center><h1>
<u>Work Experience</u>
</center></h1>

<b>Procter & Gamble Pharamceuticals</b> Cincinnati, OH <em>System Manager</em>
(June '98 - Present) 

<ul>
<li>
Project Leader for a three year global project to replace an aging 
Clinical Data Management System. Over saw the development and validation 
of numerous enhancements, managed the project plan, and  
coordinated ten different sub-teams.
<li>
Technical Leader for image storage and retrieval system that was run in a
validated environment.  Led project to achieve Y2k 
compliance and well as a year long project to port the system to 
new base technologies.
</ul>
<br>
<p>
<b>State Farm Insurance</b> Bloomington, IL <em>Systems Intern</em>
(May '97 - Aug. '97)<br>

Programmed in Assembly language on IBM mainframe system.  Member of a 5 person project
team to convert printed reports to a report archiving system. Weekly hours worked:
38

<p>


<b>Department of Computer Science</b>  Bloomington, IN
<em>Undergraduate Teaching Assistant</em>  (Jan. '96 - May '98)<br>
Instructor for two lab sections.  Lecture on using the World Wide Web and 
on the basics of HTML. Administer and grade homework. Weekly hours worked:
10<P>

<!--
<b>Syracuse Hardware</b>  Syracuse, IN  <em>Customer Assistant</em> 
(Apr. '93 - Aug. '96)<br>
Assisted customers in locating merchandise.  Suggested solutions to complicated 
problems involving plumbing and electrical work.
Minor repair of electrical equipment.  Worked 4 consecutive summers.  
Weekly hours worked:  40<P>
-->
<center><h1>
<u>Education</u>
</center></h1>

<strong>Indiana University </strong>Bloomington, IN <em>BS Computer
Science</em>
GPA <b>3.82</b>/4.00,    <b>3.95</b>/4.00 in Major<br>
<em>Minors</em>: Mathematics, Cognitive Science.<br><br>
Financed 100% of college through part-time jobs and scholarships.  
Member of the Dean's list all semesters at Indiana University.  Graduated with Highest Distinction.

<center><h1><u>
Computer Skills  
</u></h1></center>

<table border=0 cellpadding=10>
<tr>
<td align="right" valign="top">
<b>Operating Systems:</b></td>
       <td>Development experience on Windows XP, HP-UX, Sun Solaris, and
      FreeBSD.  Administration experience with FreeBSD.</td>
</tr>
<tr>

<td align="right" valign="top"><b>Languages:</b></td>
      <td> <DL><DT>Proficient in: <DD>C/C++, Java, 
       Perl, Unix shell scripting, PL/SQL, 
	Oracle Pro*C, PHP

       <DT>Knowledge of: <DD>Microsoft Visual Basic, Scheme, Microsoft Visual C++, SQR, Oracle Forms 6.0, 
       Assembly Language (Motorola + IBM Mainframe)</DL></td>
</tr>
<tr>

<td align="right" valign="top"><b>Databases:</b></td>
      <td>Development with Sybase, Informix and Oracle. Extensive
        tuning experience with Oracle.</td>
</tr>
<tr>
<td align="right" valign="top"><b>Web Development:</b></td> 
      <td>Interactive Web sites using Perl, C, and PHP</td>
</table>
<BR><BR><BR><BR>

<!--
<center><h1>
<u>Activities</u>
</center></h1>


<b>Boy Scouts of America</b>.  Eagle Scout Awarded 03/94.
Volunteered as 
Assistant Scout Master summers of  1994, 1995, and 1996.  Taught basic 
camping, first aid, and leadership skills to groups of 30.<p>

<b>Alpha Lambda Delta</b> and <b>Phi Eta Sigma</b>, Member:
scholastic
honor societies.<p>

<b>The Knights of Columbus</b>, Member:  Perform charitable acts for
the 
community. <em>Outstanding Youth Award</em> 8/93.<p>
-->

</body></html>
